on:
  workflow_dispatch:
    
jobs:
  hybrid-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a command in Ubuntu VM
        run: echo "This runs on the Ubuntu VM"


      - name: Run inside an Alpine container
        uses: docker://alpine:3.14
        with:
          entrypoint: /bin/sh
          args: |
            -C "echo 'This step runs inside an Alpine container' "

      - name: Run another command in Ubuntu VM
        run: echo "Back to the VM"

  dockerized-job:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: echo "This whole job runs inside a Node.js container"
